In [1]:
import keras
from keras.models import Sequential
from keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
from keras.optimizers import Adam
from sklearn import preprocessing
import pandas as pd
import random
import numpy as np
from keras.preprocessing import image
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.


In [2]:
data = pd.read_csv("train.csv")

In [3]:
data['NameOfPokemon'].unique()

array(['Pikachu', 'Bulbasaur', 'Charmander'], dtype=object)

In [16]:
X = data['ImageId']
y = data['NameOfPokemon']

label_encoder = preprocessing.LabelEncoder()
y = label_encoder.fit_transform(y) # Hot Encoding the data
y = to_categorical(y)
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0.

In [5]:
# Training and Testing Data
X_train = X[61:305]
X_test = X[:61]
data_dic = {}
j=0

for i in range(296,498):
    path = './Images/'+str(i-295)+'.jpg'
    data_dic[path] = y[j]
    j += 1

for i in range(203,305):
    path = './Images/'+str(i)+'.jpg'
    data_dic[path] = y[j]
    j+=1

d = data_dic # Backup
# Reshuffling the data
keys = list(data_dic.keys())
random.shuffle(keys)
shuffled_data_list = [(key, data_dic[key]) for key in keys]
print(shuffled_data_list[0])
print(shuffled_data_list[0][0])
print(shuffled_data_list[0][1])
len(shuffled_data_list)

('./Images/278.jpg', array([0., 1., 0.], dtype=float32))
./Images/278.jpg
[0. 1. 0.]


304

In [6]:
X_train = []
X_test = []
y_train = []
y_test = []

for i in range(245):
    img = image.load_img(shuffled_data_list[i][0], target_size=(75,75,3))
    img = image.img_to_array(img)
    img = img/255
    X_train.append(img)
    y_train.append(shuffled_data_list[i][1])

for i in range(245,304):
    img = image.load_img(shuffled_data_list[i][0], target_size=(75,75,3))
    img = image.img_to_array(img)
    img = img/255
    X_test.append(img)
    y_test.append(shuffled_data_list[i][1])
num_pixels =75*75*3
X_test = np.array(X_test)
X_train = np.array(X_train)
print(X_train.shape)

y_train = np.array(y_train)
y_test = np.array(y_test)

(245, 75, 75, 3)


In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(245, 75, 75, 3)
(59, 75, 75, 3)
(245, 3)
(59, 3)


In [29]:
def model():
    model = Sequential()
    model.add(Conv2D(30, (3,3), input_shape=X_train.shape[1:], activation='relu'))
    model.add(Conv2D(20, (3,3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Conv2D(10,(3,3),activation='relu'))
    model.add(Flatten())
    model.add(Dense(64, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train, batch_size=20, validation_split=0.1, epochs=35)
    return model

In [30]:
model = model()

Train on 220 samples, validate on 25 samples
Epoch 1/35
220/220 [==============================] - 2s 10ms/step - loss: 1.0723 - acc: 0.4864 - val_loss: 0.8962 - val_acc: 0.4800
Epoch 2/35
220/220 [==============================] - 2s 7ms/step - loss: 0.6459 - acc: 0.7136 - val_loss: 0.5831 - val_acc: 0.7600
Epoch 3/35
220/220 [==============================] - 2s 7ms/step - loss: 0.4548 - acc: 0.7682 - val_loss: 0.4604 - val_acc: 0.7200
Epoch 4/35
220/220 [==============================] - 2s 7ms/step - loss: 0.3353 - acc: 0.8727 - val_loss: 0.4021 - val_acc: 0.8400
Epoch 5/35
220/220 [==============================] - 2s 8ms/step - loss: 0.2382 - acc: 0.9227 - val_loss: 0.4896 - val_acc: 0.7600
Epoch 6/35
220/220 [==============================] - 2s 7ms/step - loss: 0.2113 - acc: 0.9273 - val_loss: 0.3821 - val_acc: 0.8400
Epoch 7/35
220/220 [==============================] - 2s 8ms/step - loss: 0.1352 - acc: 0.9455 - val_loss: 0.3422 - val_acc: 0.8400
Epoch 8/35
220/220 [==========

In [31]:
score = model.evaluate(X_test, y_test, verbose=2)
print(str(score[1]*100)+"%")

86.4406775620024%


In [43]:
# Testing
import cv2
img = cv2.imread("./char.jpg")
img = cv2.resize(img, (75,75))
img = np.asarray(img)
img = img.reshape(1,75,75,3)
model.predict_classes(img)

array([0], dtype=int64)